branches: ['main']
ci: true
debug: true
dryRun: false
success: false
fail: false
tagFormat: '${version}'

# Global plugin options (will be passed to all plugins)
preset: 'conventionalcommits'
gitlabUrl: 'https://gitlab.com/sprinttechnologies/mm/frontend/mithril-ui-kit.git' # your gitlab url

# Responsible for verifying conditions necessary to proceed with the release:
# configuration is correct, authentication token are valid, etc...
verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/gitlab'

# Responsible for determining the type of the next release (major, minor or patch).
# If multiple plugins with a analyzeCommits step are defined, the release type will be
# the highest one among plugins output.
# Look details at: https://github.com/semantic-release/commit-analyzer#configuration
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

# Responsible for preparing the release, for example creating or updating files
# such as package.json, CHANGELOG.md, documentation or compiled assets
# and pushing a commit.
prepare:
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/npm'
  - path: '@semantic-release/git'
    message: '[skip ci] RELEASE: ${nextRelease.version}'
    assets: ['CHANGELOG.md', 'package.json', 'package-lock.json']

# Responsible for publishing the release.
publish:
  - path: '@semantic-release/gitlab'
  - path: '@semantic-release/npm'
