/// <reference types="vitest" />

import fs from 'fs';
import { fileURLToPath, URL } from 'node:url';
import { defineConfig, type UserConfig } from 'vite';

import intro from './intro.txt?raw';
import pkg from './package.json';
import { getMatchesFromMap } from './src/hostMap';

// import dts from 'vite-plugin-dts';

console.log('-intro-', typeof intro);

const pathResolve = (path: string) => fileURLToPath(new URL(path, import.meta.url));

export default defineConfig(async ({ command, mode }): Promise<UserConfig> => {
  console.log('[vite.config]', { command, mode });

  return {
    build: {
      minify: false,
      copyPublicDir: false,
      // emptyOutDir: false, // to retain the types folder generated by tsc
      // sourcemap: true,
      target: 'esnext', // Reduce bloat from legacy polyfills.

      lib: {
        name: 'mithril',
        formats: ['es'],
        // fileName: (format) => `mithril.${format}.mjs`,
        entry: {
          index: pathResolve('./src/index.ts'),
        },
      },
      rollupOptions: {
        // external: [...Object.keys(pkg.peerDependencies)],
        treeshake: true,
        output: {
          exports: 'named',
          // intro: `${intro};`,
          globals: {
            // vue: "Vue"
          },
          // chunkFileNames: 'chunk/[name]/[hash].js',
          // assetFileNames: 'asset/[name]/[hash][extname]',
          entryFileNames: 'index.user.js',
        },
      },
    },
    plugins: [
      // https://github.com/qmhc/vite-plugin-dts
      // dts({
      //   entryRoot: './src',
      //   // cleanVueFileName: true,
      //   // insertTypesEntry: true, // adds dist/index.d.ts
      //   include: ['./src/vite-env.d.ts', '*/types.d.ts', './src/index.ts'],
      //   // exclude: ["./src/plugins"],
      //   outDir: './dist',
      //   // TO-DO: Vite should use `tsconfig.build.json` as well when it supports configuring
      //   // See: https://github.com/vitejs/vite/discussions/8483
      //   // tsconfigPath: 'tsconfig.build.json',
      //   // include: 'src',
      //   // rollupTypes: true,
      // }),
      {
        name: 'add-intro-comments',
        apply: 'build',

        writeBundle(option, bundle) {
          const [[key]] = Object.entries(bundle);

          const filePath = pathResolve(`./dist/${key}`);
          const data = fs.readFileSync(filePath, { encoding: 'utf8' });
          const introReplaced = intro
            .replace('__VERSION_FROM_PACKAGE_JSON__', pkg.version)
            .replace('__APP_URL_MATCHES__', getMatchesFromMap)
            .replace('__LAST_RELEASE__', new Date().toLocaleString('ru'));
          fs.writeFileSync(filePath, `${introReplaced}\n${data}`);
        },
      },
    ],
    resolve: { alias: { '@': pathResolve('./src') } },
  };
});
