export { notCoin } from './notCoin';
export { clixGame } from './clixGame';
export { doxCoin } from './doxCoin';
export { limeCoin } from './limeCoin';
export { tapSwap } from './tapSwap';
export { thePixels } from './thePixels';
export { arbuzApp } from './arbuzApp';
export { yesCoin } from './yesCoin';
export { mellCoin } from './mellCoin';
